// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWzXIb-yxuPxoC49MRJu_lcPBbmR7X8g',
    appId: '1:504621915820:web:1bdd90de4fd59d87948909',
    messagingSenderId: '504621915820',
    projectId: 'flutter-challenge-c6dce',
    authDomain: 'flutter-challenge-c6dce.firebaseapp.com',
    storageBucket: 'flutter-challenge-c6dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49zHSwCtdzBX7YQuDDA0vDzNl38GHYfE',
    appId: '1:504621915820:android:f7d99a1695aff891948909',
    messagingSenderId: '504621915820',
    projectId: 'flutter-challenge-c6dce',
    storageBucket: 'flutter-challenge-c6dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcIllQsmlpy9XoD-aG42H49RJMutwcVA',
    appId: '1:504621915820:ios:9809f7ee24d3633d948909',
    messagingSenderId: '504621915820',
    projectId: 'flutter-challenge-c6dce',
    storageBucket: 'flutter-challenge-c6dce.appspot.com',
    iosClientId: '504621915820-eufsvpthk2keajcvgqvp1v9c0votqkfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge',
  );
}
